format_version: 3
pipelines:
  Cogniflect:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Compile:
            timeout: 0
            tasks:
            - exec:
                command: pwd
                run_if: passed
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
            - exec:
                arguments:
                - run
                - --rm
                - --name
                - node-builder
                - --volume
                - node_modules:/app/node_modules
                - --volume
                - /volume1/docker/godata/pipelines/Cogniflect:/app
                - --entrypoint
                - /usr/local/bin/yarn
                - --workdir
                - /app
                - node:10
                command: docker
                run_if: passed
